PROJECT_NAME = "Simple Virtual Camera"

ASSETS_PATH_FORMAT = "assets/{0}"
ASSETS_FILES = list(map(
	lambda file_name: ASSETS_PATH_FORMAT.format(file_name),
	["figure1.json"]
))

ENTITIES_KEY = "entities"
POINTS_KEY = "points"
EDGES_KEY = "edges"
WALLS_KEY = "walls"

X_KEY = "x"
Y_KEY = "y"
Z_KEY = "z"

WINDOW_X_SIZE = 700
WINDOW_Y_SIZE = 500

X_SHIFT_KEY = "X_SHIFT"
Y_SHIFT_KEY = "Y_SHIFT"
Z_SHIFT_KEY = "Z_SHIFT"

X_ROTATION_KEY = "X_ROTATION"
Y_ROTATION_KEY = "Y_ROTATION"
Z_ROTATION_KEY = "Z_ROTATION"

ZOOM_KEY = "ZOOM"

SHIFT_QUANTUM = 10
ROTATION_QUANTUM = 15
ZOOM_QUANTUM = 5

LINE_WIDTH = 1
